spring:
  application:
    name: M2J2
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
    url: jdbc:h2:mem:testdb
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true