spring:
  application:
    name: HaruSeoul
  web:
    resources:
      static-locations: file:./uploads/

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

server:
  port: 8083

